name: Install OpenCL
author: KhrySystem
description: Download and build OpenCL from source for use in Github workflow

inputs:
  version:
    description: Describes a tagged branch of the OpenCL SDK. 
    required: true
  cache:
    description: Use @actions/cache to help development.
    required: false
    default: true
  cmake_args:
    description: The arguments to append onto the CMake build task.
    required: false
    default: ''
  path:
    description: Path to install OpenCL into.
    required: false
    default: ${{github.workspace}}/opencl-sdk
  
runs:
  using: 'composite'
  steps:
  - name: Install Dependencies
    shell: bash
    run: |
      if [[ $RUNNER_OS == 'Linux' ]]; then
        sudo apt-get install build-essential libgl1-mesa-dev libvulkan-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev libxrandr-dev libxxf86vm-dev mesa-common-dev libudev-dev freeglut3 freeglut3-dev binutils-gold
      fi

  - if: ${{ inputs.cache }} == true
    id: opencl_cache
    name: Check OpenCL Cache
    uses: actions/cache@v3
    with:
      path: |
        ${{ inputs.path }}
      key: __${{ runner.os }}-opencl${{ inputs.version }}__${{ inputs.cmake-args }}
      restore-keys: |
        __${{runner.os }}-opencl__

  - if: ${{ steps.opencl_cache.outputs.cache-hit != 'true' }}
    name: Download OpenCL
    shell: bash
    run: git clone --recursive --branch ${{ inputs.version }} https://github.com/KhronosGroup/OpenCL-SDK.git ${{ inputs.path }}.cache

  - name: Build OpenCL
    shell: bash
    run: |
      cmake -S ${{ inputs.path }}.cache -B ${{ inputs.path }} ${{ inputs.cmake_args }}
      cmake --build ${{inputs.path }} --target install

  - name: Export Symbols
    shell: bash
    run: |
      echo "OpenCL_ROOT=${{ inputs.path }}" >> $GITHUB_OUTPUT
      echo "OpenCL_INSTALL_DIR_ROOT=${{ inputs.path }}.cache/install/include" >> $GITHUB_OUTPUT
      echo "OpenCL_LIBRARY=${{ inputs.path }}.cache/bin/opencl.lib" >> $GITHUB_OUTPUT
