name: Install OpenCL
author: KhrySystem
description: Download and build OpenCL from source for use in Github workflow

inputs:
  version:
    description: Describes a tagged branch of the OpenCL SDK. 
    required: true
  cache:
    description: Use @actions/cache to help development.
    required: false
    default: true
  cmake_args:
    description: The arguments to append onto the CMake build task.
    required: false
    default: ''
  path:
    description: Path to install OpenCL into.
    required: false
    default: ${{github.workspace}}/opencl-sdk
  
runs:
  using: 'composite'
  steps:
  - if: ${{ inputs.cache }} == true
    id: opencl_cache
    name: Check OpenCL Cache
    uses: actions/cache@v3
    with:
      path: |
        ${{ inputs.path }}
        ${{ inputs.path }}.cache
      key: _${{ runner.os }}_opencl${{ inputs.version }}_${{ inputs.path }}_
      restore-keys: |
        _${{ runner.os }}_opencl${{ inputs.version }}__
        __opencl__

  - if: ${{ steps.opencl_cache.outputs.cache-hit != 'true' }}
    name: Download OpenCL
    run: git clone --depth 1 --recursive --branch ${{ inputs.version }} https://github.com/KhronosGroup/OpenCL-SDK.git ${{ inputs.path }}.cache

  - name: Build OpenCL
    run: |
      cmake -S ${{ inputs.path }}.cache -B ${{ inputs.path }} ${{ inputs.cmake_args }}
      cmake --build ${{inputs.path }} --target install

  - name: Export Symbols
    run: |
      echo "OPENCL_ROOT=${{ inputs.path }}" >> $GITHUB_OUTPUT
