name: Test Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3

      - name: Run Action
        uses: ./